"""
State definition for the PaperPilot multi-agent graph.

This module defines the shared AgentState schema. All nodes in the LangGraph
read from and write to this state.

Why TypedDict?
    LangGraph uses Python's typing.TypedDict as its primary state representation.
    Each key represents a state variable. When a node returns a dictionary,
    LangGraph updates the shared state by merging the returned dictionary keys
    into the state.

Why Reducers?
    By default, LangGraph overwrites state values: if Node A sets `query = "foo"`
    and Node B sets `query = "bar"`, the final state value is "bar".

    For conversation history (`messages`), we do NOT want to overwrite the values.
    We want to append new messages. We specify a custom reducer (annotated via
    `Annotated[list, add_messages]`) to instruct LangGraph to run the `add_messages`
    reducer, which merges and appends message lists instead of overwriting them.
"""

from __future__ import annotations

from typing import Annotated, TypedDict
from uuid import UUID

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

from paperpilot.core.models import PaperMetadata, TextChunk


# Custom reducer to append list items (like found papers) instead of overwriting.
# If a key is annotated with this, updates are appended to the list.
def append_reducer(left: list | None, right: list | None) -> list:
    """Reducer that appends new items to a list.

    Handles None inputs gracefully.
    """
    left = left or []
    right = right or []
    return left + right


class AgentState(TypedDict):
    """The shared state dictionary for the PaperPilot multi-agent workflow.

    Each key defines a state variable available to all nodes. Annotations
    with functions (like `add_messages` or `append_reducer`) define custom merge
    behavior for updates.

    Attributes:
        query: The raw natural language input from the user.
        search_query: Search keywords formulated by the planner.
        discovered_papers: List of candidate papers found from searches.
                           Accumulates papers using `append_reducer`.
        selected_papers: List of papers chosen for processing and download.
        retrieved_context: Chunks retrieved by the vector database.
        generated_answer: Current response draft generated by the Tutor.
        critic_feedback: Structural critique logs from the Critic.
        critic_approved: Gatekeeper flag. Nodes set this to True/False.
        retry_count: Counter tracking generation cycles to prevent infinite loops.
        messages: Standard conversation history (managed via `add_messages`).
    """

    query: str
    search_query: str
    discovered_papers: Annotated[list[PaperMetadata], append_reducer]
    selected_papers: list[PaperMetadata]
    retrieved_context: list[TextChunk]
    generated_answer: str
    critic_feedback: str
    critic_approved: bool
    retry_count: int
    messages: Annotated[list[BaseMessage], add_messages]
    plan_steps: list[str]
    plan_nodes: list[str]
    plan_queries: list[str]
    current_step_idx: int
    step_answers: list[str]
    tutor_difficulty: str
    workspace_id: UUID | None

